base_url = "https://resume.alongwy.top"
compile_sass = true
title = "Feng"
description = "A clean resume theme"
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
first_name = "Feng"
last_name = "Yunlong"
address = "Harbin, China"
email = "ylfeng@ir.hit.edu.cn"
favicon = "/favicon.ico"
avatar = "/media/avatar.png"

katex = false
show_about = true
show_skills = true
show_projects = true
show_opensource = true
show_publications = true
show_experience = true
show_education = true
show_blog = true
